# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FRPCpp <- function(returns, factors, misspecification_robust = TRUE, include_standard_errors = FALSE, hac_prewhite = FALSE, target_level_gkr2014_screening = 0.) {
    .Call(`_intrinsicFRP_FRPCpp`, returns, factors, misspecification_robust, include_standard_errors, hac_prewhite, target_level_gkr2014_screening)
}

GKRFactorScreeningCpp <- function(returns, factors, target_level = 0.05, hac_prewhite = FALSE) {
    .Call(`_intrinsicFRP_GKRFactorScreeningCpp`, returns, factors, target_level, hac_prewhite)
}

HACCovarianceMatrixCpp <- function(series, prewhite = FALSE) {
    .Call(`_intrinsicFRP_HACCovarianceMatrixCpp`, series, prewhite)
}

HACVarianceCpp <- function(series, prewhite = FALSE) {
    .Call(`_intrinsicFRP_HACVarianceCpp`, series, prewhite)
}

HJMisspecificationDistanceCpp <- function(returns, factors, ci_coverage = .95, hac_prewhite = FALSE) {
    .Call(`_intrinsicFRP_HJMisspecificationDistanceCpp`, returns, factors, ci_coverage, hac_prewhite)
}

ChenFang2019BetaRankTestCpp <- function(returns, factors, n_bootstrap = 500L, target_level_kp2006_rank_test = 0.05) {
    .Call(`_intrinsicFRP_ChenFang2019BetaRankTestCpp`, returns, factors, n_bootstrap, target_level_kp2006_rank_test)
}

IterativeKleibergenPaap2006BetaRankTestCpp <- function(returns, factors, target_level = .05) {
    .Call(`_intrinsicFRP_IterativeKleibergenPaap2006BetaRankTestCpp`, returns, factors, target_level)
}

OracleTFRPCpp <- function(returns, factors, penalty_parameters, weighting_type, tuning_type, one_stddev_rule, gcv_scaling_n_assets, gcv_identification_check, target_level_kp2006_rank_test, n_folds, n_train_observations, n_test_observations, roll_shift, relaxed, include_standard_errors, hac_prewhite) {
    .Call(`_intrinsicFRP_OracleTFRPCpp`, returns, factors, penalty_parameters, weighting_type, tuning_type, one_stddev_rule, gcv_scaling_n_assets, gcv_identification_check, target_level_kp2006_rank_test, n_folds, n_train_observations, n_test_observations, roll_shift, relaxed, include_standard_errors, hac_prewhite)
}

TFRPCpp <- function(returns, factors, include_standard_errors, hac_prewhite = FALSE) {
    .Call(`_intrinsicFRP_TFRPCpp`, returns, factors, include_standard_errors, hac_prewhite)
}

