# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

OptimalAdaptiveIFRPGCVCpp <- function(returns, factors, covariance_factors_returns, variance_returns, mean_returns, penalty_parameters, weighting_type = 'c', gcv_vr_weighting = FALSE, gcv_aic_scaling = TRUE, one_stddev_rule = FALSE, relaxed = FALSE) {
    .Call(`_intrinsicFRP_OptimalAdaptiveIFRPGCVCpp`, returns, factors, covariance_factors_returns, variance_returns, mean_returns, penalty_parameters, weighting_type, gcv_vr_weighting, gcv_aic_scaling, one_stddev_rule, relaxed)
}

OptimalAdaptiveIFRPCVCpp <- function(returns, factors, covariance_factors_returns, variance_returns, mean_returns, penalty_parameters, weighting_type = 'c', n_folds = 5L, one_stddev_rule = FALSE, relaxed = FALSE) {
    .Call(`_intrinsicFRP_OptimalAdaptiveIFRPCVCpp`, returns, factors, covariance_factors_returns, variance_returns, mean_returns, penalty_parameters, weighting_type, n_folds, one_stddev_rule, relaxed)
}

OptimalAdaptiveIFRPRVCpp <- function(returns, factors, covariance_factors_returns, variance_returns, mean_returns, penalty_parameters, weighting_type = 'c', n_train_observations = 120L, n_test_observations = 12L, roll_shift = 12L, one_stddev_rule = FALSE, relaxed = FALSE) {
    .Call(`_intrinsicFRP_OptimalAdaptiveIFRPRVCpp`, returns, factors, covariance_factors_returns, variance_returns, mean_returns, penalty_parameters, weighting_type, n_train_observations, n_test_observations, roll_shift, one_stddev_rule, relaxed)
}

AdaptiveIFRPCpp <- function(ifrp, weights, penalty_parameter) {
    .Call(`_intrinsicFRP_AdaptiveIFRPCpp`, ifrp, weights, penalty_parameter)
}

RelaxedAdaptiveIFRPCpp <- function(aifrp, covariance_factors_returns, variance_returns, mean_returns) {
    .Call(`_intrinsicFRP_RelaxedAdaptiveIFRPCpp`, aifrp, covariance_factors_returns, variance_returns, mean_returns)
}

StandardErrorsAdaptiveIFRPCpp <- function(adaptive_ifrp, returns, factors, covariance_factors_returns, variance_returns, mean_returns, mean_factors) {
    .Call(`_intrinsicFRP_StandardErrorsAdaptiveIFRPCpp`, adaptive_ifrp, returns, factors, covariance_factors_returns, variance_returns, mean_returns, mean_factors)
}

AdaptiveWeightsCpp <- function(returns, factors, type = 'c') {
    .Call(`_intrinsicFRP_AdaptiveWeightsCpp`, returns, factors, type)
}

FRPCpp <- function(beta, mean_returns) {
    .Call(`_intrinsicFRP_FRPCpp`, beta, mean_returns)
}

KRSFRPCpp <- function(beta, mean_returns, weighting_matrix) {
    .Call(`_intrinsicFRP_KRSFRPCpp`, beta, mean_returns, weighting_matrix)
}

StandardErrorsFRPCpp <- function(frp, returns, factors, beta, covariance_factors_returns, variance_returns, variance_factors, mean_returns, mean_factors) {
    .Call(`_intrinsicFRP_StandardErrorsFRPCpp`, frp, returns, factors, beta, covariance_factors_returns, variance_returns, variance_factors, mean_returns, mean_factors)
}

StandardErrorsKRSFRPCpp <- function(krs_frp, returns, factors, beta, covariance_factors_returns, variance_returns, variance_factors, mean_returns, mean_factors) {
    .Call(`_intrinsicFRP_StandardErrorsKRSFRPCpp`, krs_frp, returns, factors, beta, covariance_factors_returns, variance_returns, variance_factors, mean_returns, mean_factors)
}

IFRPCpp <- function(covariance_factors_returns, variance_returns, mean_returns) {
    .Call(`_intrinsicFRP_IFRPCpp`, covariance_factors_returns, variance_returns, mean_returns)
}

StandardErrorsIFRPCpp <- function(ifrp, returns, factors, covariance_factors_returns, variance_returns, mean_returns, mean_factors) {
    .Call(`_intrinsicFRP_StandardErrorsIFRPCpp`, ifrp, returns, factors, covariance_factors_returns, variance_returns, mean_returns, mean_factors)
}

